[
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 1,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 2,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 3,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 4,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 5,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 6,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 7,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 0,
    global_id_y: 1,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 1,
    global_id_y: 1,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 2,
    global_id_y: 1,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 3,
    global_id_y: 1,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 4,
    global_id_y: 1,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 5,
    global_id_y: 1,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 6,
    global_id_y: 1,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 7,
    global_id_y: 1,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 0,
    global_id_y: 2,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 1,
    global_id_y: 2,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 2,
    global_id_y: 2,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 3,
    global_id_y: 2,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 4,
    global_id_y: 2,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 5,
    global_id_y: 2,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 6,
    global_id_y: 2,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 7,
    global_id_y: 2,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 0,
    global_id_y: 3,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 1,
    global_id_y: 3,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 2,
    global_id_y: 3,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 3,
    global_id_y: 3,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 4,
    global_id_y: 3,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 5,
    global_id_y: 3,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 6,
    global_id_y: 3,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 7,
    global_id_y: 3,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 0,
    global_id_y: 4,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 1,
    global_id_y: 4,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 2,
    global_id_y: 4,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 3,
    global_id_y: 4,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 4,
    global_id_y: 4,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 5,
    global_id_y: 4,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 6,
    global_id_y: 4,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 7,
    global_id_y: 4,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 0,
    global_id_y: 5,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 1,
    global_id_y: 5,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 2,
    global_id_y: 5,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 3,
    global_id_y: 5,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 4,
    global_id_y: 5,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 5,
    global_id_y: 5,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 6,
    global_id_y: 5,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 7,
    global_id_y: 5,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 0,
    global_id_y: 6,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 1,
    global_id_y: 6,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 2,
    global_id_y: 6,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 3,
    global_id_y: 6,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 4,
    global_id_y: 6,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 5,
    global_id_y: 6,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 6,
    global_id_y: 6,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 7,
    global_id_y: 6,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 0,
    global_id_y: 7,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 1,
    global_id_y: 7,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 2,
    global_id_y: 7,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 3,
    global_id_y: 7,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 4,
    global_id_y: 7,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 5,
    global_id_y: 7,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 6,
    global_id_y: 7,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 145,
    array_size: 8,
    global_id_x: 7,
    global_id_y: 7,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 8,
    workgroup_id_y: 0,
    workgroup_size_y: 8,
    workgroup_id_z: 0,
    workgroup_size_z: 1,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
  {
    max_array_size: 0,
    array_size: 0,
    global_id_x: 0,
    global_id_y: 0,
    global_id_z: 0,
    workgroup_id_x: 0,
    workgroup_size_x: 0,
    workgroup_id_y: 0,
    workgroup_size_y: 0,
    workgroup_id_z: 0,
    workgroup_size_z: 0,
  },
];
